version: "3.8"

services:
  app:
    image: tgbot
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
